### PR TITLE
refactored dim

### PR DESCRIPTION
**Pull request by idanmel**
Here's what I mean by converting Dim to String (List String)

I think everything still works, right?

### CODE REVIEW

**Comment by objarni** [comment]
I'm sure everything still works, however, the reason Dim has the three parameters:

- first
- second
- rest

.. is because a dimension in the resulting name with only a single possible value, say "1", does not make sense in my humble opinion - it is not random anymore but fixed. If you want a fixed part of the string, just use "1-" ++ randomName or similar casual string formatting :)

Having both a first and a second parameter, and 0 or more elements in the rest list, ensures at least 2 possible values in each dimension.

**Comment by idanmel** [comment]
When I think of myself as someone who uses this package, I would prefer to write:
`dimension "2" [ "3", "4", "5" ]`
then 
`dimension "2" "3" [ "4", "5" ]`

Also, now if I wanted to create varients of monkeys, I could do:
```elm
space      { starts = dimension "2" [ "3", "4", "5" ]
                , mids = dimension "happy" [ "humble", "stubborn" ]
                , ends = dimension "monkeys" []
                }
```
Which will still give me 12 options to randomize from.

**Comment by objarni** [comment]
If you always want the names to end with "-monkeys", you can write something like:

```
update msg model =
    let
        ( name, newSeed ) =
            Random.step randomName model.seed
        groupName = rawName ++ "-monkeys"
    in
    ....
```

Or even simpler - set both first and second parameter to "monkey":

```
    let
        space  { starts = dimension "2" "3" [ "4", "5" ]
                    , mids = dimension "happy" "humble" [ "stubborn" ]
                    , ends = dimension "monkeys" "monkeys" []
                    }
        ( groupName, newSeed ) =
            Random.step (randomNameFromSpace space) model.seed
    in
```

**Comment by idanmel** [comment]
The first example will create a name with 3 dashes when I want a name with 2 dashes.

As for the second one, it seems less intuitive for me to have to write the same string twice followed by an empty list, instead of just one string followed by an empty list.

**Pull request closed without merging**
